# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-q']
      timeout: 45s
      interval: 10s
      retries: 10
  adminer:
    image: adminer
    container_name: database-dashboard
    restart: always
    ports:
      - 8080:8080
  app:
    env_file:
      - .env
    container_name: app
    build: .
    environment:
      - APP_PORT=3333
      - DATABASE_URL=postgresql://postgres:example@db/db_transferencia?schema=public
    command: >
      sh -c "npm run db:migrate:dev && npm start"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      db:
        condition: service_healthy
