# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: database-dashboard
    restart: always
    ports:
      - 8080:8080
