name: Release Workflow
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: my_password

on: ['pull_request']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use nodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Static Analysis
        run: npm run lint && npm run style:check

      - name: Run all tests
        run: npm run test:ci

      - name: Run mutation tests
        run: npm run test:mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
